### ISSUE TITLE
Boot failed

### ISSUE THREAD

**Issue by begoat** [Cleafy/sxkdvm#1]
On Ubuntu 16.04 Kernel version 4.4
i7-6700U

Boot hang.
The verbose message is something related to log, then it stuck.
I use mac-hdd.img produced by OSX-KVM project.
Then mkdir backing in current dir and place it into the dir.
Run the command and that's all.

Could you detail your documentation? Or give me some suggestion?

**Comment by thypon** [comment]
Could you provide the logs about the issue you encountered?

Was the image working with https://github.com/Cleafy/sxkdvm and which version of OSX have you tried running?

Currently, https://github.com/Cleafy/sxkdvm supports OSX 'till  10.11.x (El Capitan).

**Comment by begoat** [comment]
Sorry, maybe I found myself install OS X EI Captain 10.11.6 failed. 
when i boot use the script called boot-macOS.sh,
i got error like this:
```
ehci warning: guest requested more bytes than allowed
processing error - resetting ehci HC
```
and the screen stuck at the apple logo with grey background.

Could you give me some advice though i know this situration is not a part of your project.

**Comment by thypon** [comment]
The ehci warning you experiment is only a warning. I need something more, such as the boot log of OSX in order to troubleshoot the problem. It is possible to instruct the bootloader to boot in verbose mode.

My best guesses are that you forgot to ignore msrs[1], or maybe you have other virtualization product installed (such as VirtualBox). In that case, KVM is not enabled and the boot is not stucked, is only very very slow.

Let me know if the problem persists.

[1]: echo 1 > /sys/module/kvm/parameters/ignore_msrs

**Comment by begoat** [comment]
Thank you. I remember that I typed this command before. And I am not sure kvm is enabled, I will try it later when I go back home:)

**Comment by begoat** [comment]
I tried upgrade qemu to version2.9 and update my kernel to 4.13 ubuntu 16.04.
and I tried remove virtualbox and execute `echo 1 > /sys/module/kvm/parameters/ignore_msrs`
But all these doesn't work.

I enter verbose mode by adding -v in bootloader.

The output is:
```
QEMU 2.9.1 monitor - type 'help' for more information
(qemu) qemu-system-x86_64: warning: Unknown firmware file in legacy mode: genroms/multiboot.bin
audio: Could not init `oss' audio driver
ehci warning: guest requested more bytes than allowed
processing error - resetting ehci HC
```

then it stuck. The kvm window is black with no output.
And the console doesn't update anymore.

Could you give me some suggestions? Thank you.

**Comment by thypon** [comment]
As I said, I don't think the QEmu logs are that useful.

**Comment by begoat** [comment]
in verbose mode, no output after
```
CPU is Intel Core 2 Duo P9xxx
System UUID: incorrect or not present. Fixing 00112233-4455-6677-8899-AABBCCDDEEFF
[ACOI PATCHER]
Adding booter spec to hte platform expert
Attempting to load drivers ffrom standard repositories:
      - Third party extensins search path: /Library/Extensions
      - Apple extensions search path: /System/Library/Extensions
```

**Comment by begoat** [comment]
Thank you anyway for your help. I will try it out later on if necessary.
